### ISSUE TITLE
ili9341 hardware spi

### ISSUE THREAD

**Issue by sinrab** [zxfr/Pixels#1]
I have a TFT01-2.2SP display. The LCD in the TFT01 is ILI9341. It's a 240 \* 320 (resolution).
In the software SPI with Pixels library it works.
Is it possible to use hardware SPI? How to do it?

**Comment by zxfr** [comment]
In an ideal case it would be sufficient to substitute
#include &lt;Pixels_SPIsw.h&gt;
with
#include &lt;Pixels_SPIhw.h&gt;

Does it work for you?

**Comment by sinrab** [comment]
I did it! It works! My simple test code

---

#include "Pixels_SPIhw.h"
#include "Pixels_ILI9341.h"
Pixels pxs(240, 320);

void setup() {
    pxs.setSpiPins(13, 11, 7, 5, 6); // TFT01-2.2SP display ILI9341(SCK, MOSI, CS, RESET, DC)
    pxs.init();
    pxs.setBackground(0, 0, 0);
    pxs.setColor(0, 255, 0);
    pxs.clear();
    pxs.fillRectangle(10, 10, 100, 100);
}

void loop() {

## }

After loading the sketch does not work, but after the switch-off and turn on Arduino sketch works! Probably because the Arduino is powered by 3.3 volts.
